import { UserRole, MembershipRole, PlanTier } from '../types';
export declare const ROLES: {
    readonly SUPER_ADMIN: UserRole.SUPER_ADMIN;
    readonly TENANT_ADMIN: UserRole.TENANT_ADMIN;
    readonly INSTRUCTOR: UserRole.INSTRUCTOR;
    readonly STUDENT: UserRole.STUDENT;
    readonly PARENT: UserRole.PARENT;
    readonly SUPPORT: UserRole.SUPPORT;
    readonly OBSERVER: UserRole.OBSERVER;
};
export declare const MEMBERSHIP_ROLES: {
    readonly OWNER: MembershipRole.OWNER;
    readonly ADMIN: MembershipRole.ADMIN;
    readonly MEMBER: MembershipRole.MEMBER;
};
export declare const PLAN_TIERS: {
    readonly STARTER: PlanTier.STARTER;
    readonly PROFESSIONAL: PlanTier.PROFESSIONAL;
    readonly ENTERPRISE: PlanTier.ENTERPRISE;
};
export declare const PERMISSIONS: {
    readonly DASHBOARD_VIEW: "dashboard:view";
    readonly USERS_VIEW: "users:view";
    readonly USERS_CREATE: "users:create";
    readonly USERS_EDIT: "users:edit";
    readonly USERS_DELETE: "users:delete";
    readonly USERS_INVITE: "users:invite";
    readonly TENANTS_VIEW: "tenants:view";
    readonly TENANTS_CREATE: "tenants:create";
    readonly TENANTS_EDIT: "tenants:edit";
    readonly TENANTS_DELETE: "tenants:delete";
    readonly STUDENTS_VIEW: "students:view";
    readonly STUDENTS_CREATE: "students:create";
    readonly STUDENTS_EDIT: "students:edit";
    readonly STUDENTS_DELETE: "students:delete";
    readonly COURSES_VIEW: "courses:view";
    readonly COURSES_CREATE: "courses:create";
    readonly COURSES_EDIT: "courses:edit";
    readonly COURSES_DELETE: "courses:delete";
    readonly FACULTY_VIEW: "faculty:view";
    readonly FACULTY_CREATE: "faculty:create";
    readonly FACULTY_EDIT: "faculty:edit";
    readonly FACULTY_DELETE: "faculty:delete";
    readonly DEPARTMENTS_VIEW: "departments:view";
    readonly DEPARTMENTS_CREATE: "departments:create";
    readonly DEPARTMENTS_EDIT: "departments:edit";
    readonly DEPARTMENTS_DELETE: "departments:delete";
    readonly ANALYTICS_VIEW: "analytics:view";
    readonly ANALYTICS_EXPORT: "analytics:export";
    readonly SETTINGS_VIEW: "settings:view";
    readonly SETTINGS_EDIT: "settings:edit";
    readonly AI_ACCESS: "ai:access";
    readonly AI_ADMIN: "ai:admin";
    readonly CONNECTORS_VIEW: "connectors:view";
    readonly CONNECTORS_MANAGE: "connectors:manage";
    readonly AUDIT_VIEW: "audit:view";
};
export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export declare const ROLE_PERMISSIONS: Record<UserRole, Permission[]>;
export declare const HTTP_STATUS: {
    readonly OK: 200;
    readonly CREATED: 201;
    readonly ACCEPTED: 202;
    readonly NO_CONTENT: 204;
    readonly BAD_REQUEST: 400;
    readonly UNAUTHORIZED: 401;
    readonly FORBIDDEN: 403;
    readonly NOT_FOUND: 404;
    readonly CONFLICT: 409;
    readonly UNPROCESSABLE_ENTITY: 422;
    readonly TOO_MANY_REQUESTS: 429;
    readonly INTERNAL_SERVER_ERROR: 500;
    readonly SERVICE_UNAVAILABLE: 503;
};
export declare const ERROR_CODES: {
    readonly VALIDATION_ERROR: "VALIDATION_ERROR";
    readonly UNAUTHORIZED: "UNAUTHORIZED";
    readonly FORBIDDEN: "FORBIDDEN";
    readonly NOT_FOUND: "NOT_FOUND";
    readonly CONFLICT: "CONFLICT";
    readonly INTERNAL_ERROR: "INTERNAL_ERROR";
    readonly TENANT_NOT_FOUND: "TENANT_NOT_FOUND";
    readonly USER_NOT_FOUND: "USER_NOT_FOUND";
    readonly EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS";
    readonly SLUG_ALREADY_EXISTS: "SLUG_ALREADY_EXISTS";
    readonly INVALID_CREDENTIALS: "INVALID_CREDENTIALS";
    readonly TOKEN_EXPIRED: "TOKEN_EXPIRED";
    readonly RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED";
};
export declare const DEFAULTS: {
    readonly PAGINATION_PAGE: 1;
    readonly PAGINATION_PER_PAGE: 20;
    readonly PAGINATION_MAX_PER_PAGE: 100;
    readonly PASSWORD_MIN_LENGTH: 8;
    readonly PASSWORD_MAX_LENGTH: 100;
    readonly SESSION_MAX_AGE_MS: number;
    readonly INVITATION_EXPIRY_MS: number;
    readonly VERIFICATION_TOKEN_EXPIRY_MS: number;
    readonly MAX_FILE_SIZE_BYTES: number;
    readonly RATE_LIMIT_WINDOW_MS: number;
    readonly RATE_LIMIT_MAX_REQUESTS: 100;
};
