"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULTS = exports.ERROR_CODES = exports.HTTP_STATUS = exports.ROLE_PERMISSIONS = exports.PERMISSIONS = exports.PLAN_TIERS = exports.MEMBERSHIP_ROLES = exports.ROLES = void 0;
const types_1 = require("../types");
exports.ROLES = {
    SUPER_ADMIN: types_1.UserRole.SUPER_ADMIN,
    TENANT_ADMIN: types_1.UserRole.TENANT_ADMIN,
    INSTRUCTOR: types_1.UserRole.INSTRUCTOR,
    STUDENT: types_1.UserRole.STUDENT,
    PARENT: types_1.UserRole.PARENT,
    SUPPORT: types_1.UserRole.SUPPORT,
    OBSERVER: types_1.UserRole.OBSERVER,
};
exports.MEMBERSHIP_ROLES = {
    OWNER: types_1.MembershipRole.OWNER,
    ADMIN: types_1.MembershipRole.ADMIN,
    MEMBER: types_1.MembershipRole.MEMBER,
};
exports.PLAN_TIERS = {
    STARTER: types_1.PlanTier.STARTER,
    PROFESSIONAL: types_1.PlanTier.PROFESSIONAL,
    ENTERPRISE: types_1.PlanTier.ENTERPRISE,
};
exports.PERMISSIONS = {
    DASHBOARD_VIEW: 'dashboard:view',
    USERS_VIEW: 'users:view',
    USERS_CREATE: 'users:create',
    USERS_EDIT: 'users:edit',
    USERS_DELETE: 'users:delete',
    USERS_INVITE: 'users:invite',
    TENANTS_VIEW: 'tenants:view',
    TENANTS_CREATE: 'tenants:create',
    TENANTS_EDIT: 'tenants:edit',
    TENANTS_DELETE: 'tenants:delete',
    STUDENTS_VIEW: 'students:view',
    STUDENTS_CREATE: 'students:create',
    STUDENTS_EDIT: 'students:edit',
    STUDENTS_DELETE: 'students:delete',
    COURSES_VIEW: 'courses:view',
    COURSES_CREATE: 'courses:create',
    COURSES_EDIT: 'courses:edit',
    COURSES_DELETE: 'courses:delete',
    FACULTY_VIEW: 'faculty:view',
    FACULTY_CREATE: 'faculty:create',
    FACULTY_EDIT: 'faculty:edit',
    FACULTY_DELETE: 'faculty:delete',
    DEPARTMENTS_VIEW: 'departments:view',
    DEPARTMENTS_CREATE: 'departments:create',
    DEPARTMENTS_EDIT: 'departments:edit',
    DEPARTMENTS_DELETE: 'departments:delete',
    ANALYTICS_VIEW: 'analytics:view',
    ANALYTICS_EXPORT: 'analytics:export',
    SETTINGS_VIEW: 'settings:view',
    SETTINGS_EDIT: 'settings:edit',
    AI_ACCESS: 'ai:access',
    AI_ADMIN: 'ai:admin',
    CONNECTORS_VIEW: 'connectors:view',
    CONNECTORS_MANAGE: 'connectors:manage',
    AUDIT_VIEW: 'audit:view',
};
exports.ROLE_PERMISSIONS = {
    [types_1.UserRole.SUPER_ADMIN]: Object.values(exports.PERMISSIONS),
    [types_1.UserRole.TENANT_ADMIN]: [
        exports.PERMISSIONS.DASHBOARD_VIEW,
        exports.PERMISSIONS.USERS_VIEW,
        exports.PERMISSIONS.USERS_CREATE,
        exports.PERMISSIONS.USERS_EDIT,
        exports.PERMISSIONS.USERS_DELETE,
        exports.PERMISSIONS.USERS_INVITE,
        exports.PERMISSIONS.STUDENTS_VIEW,
        exports.PERMISSIONS.STUDENTS_CREATE,
        exports.PERMISSIONS.STUDENTS_EDIT,
        exports.PERMISSIONS.STUDENTS_DELETE,
        exports.PERMISSIONS.COURSES_VIEW,
        exports.PERMISSIONS.COURSES_CREATE,
        exports.PERMISSIONS.COURSES_EDIT,
        exports.PERMISSIONS.COURSES_DELETE,
        exports.PERMISSIONS.FACULTY_VIEW,
        exports.PERMISSIONS.FACULTY_CREATE,
        exports.PERMISSIONS.FACULTY_EDIT,
        exports.PERMISSIONS.FACULTY_DELETE,
        exports.PERMISSIONS.DEPARTMENTS_VIEW,
        exports.PERMISSIONS.DEPARTMENTS_CREATE,
        exports.PERMISSIONS.DEPARTMENTS_EDIT,
        exports.PERMISSIONS.DEPARTMENTS_DELETE,
        exports.PERMISSIONS.ANALYTICS_VIEW,
        exports.PERMISSIONS.ANALYTICS_EXPORT,
        exports.PERMISSIONS.SETTINGS_VIEW,
        exports.PERMISSIONS.SETTINGS_EDIT,
        exports.PERMISSIONS.AI_ACCESS,
        exports.PERMISSIONS.AI_ADMIN,
        exports.PERMISSIONS.CONNECTORS_VIEW,
        exports.PERMISSIONS.CONNECTORS_MANAGE,
        exports.PERMISSIONS.AUDIT_VIEW,
    ],
    [types_1.UserRole.INSTRUCTOR]: [
        exports.PERMISSIONS.DASHBOARD_VIEW,
        exports.PERMISSIONS.STUDENTS_VIEW,
        exports.PERMISSIONS.COURSES_VIEW,
        exports.PERMISSIONS.COURSES_EDIT,
        exports.PERMISSIONS.AI_ACCESS,
        exports.PERMISSIONS.ANALYTICS_VIEW,
    ],
    [types_1.UserRole.STUDENT]: [
        exports.PERMISSIONS.DASHBOARD_VIEW,
        exports.PERMISSIONS.COURSES_VIEW,
        exports.PERMISSIONS.AI_ACCESS,
    ],
    [types_1.UserRole.PARENT]: [exports.PERMISSIONS.DASHBOARD_VIEW, exports.PERMISSIONS.STUDENTS_VIEW],
    [types_1.UserRole.SUPPORT]: [
        exports.PERMISSIONS.DASHBOARD_VIEW,
        exports.PERMISSIONS.USERS_VIEW,
        exports.PERMISSIONS.TENANTS_VIEW,
        exports.PERMISSIONS.STUDENTS_VIEW,
        exports.PERMISSIONS.COURSES_VIEW,
        exports.PERMISSIONS.FACULTY_VIEW,
        exports.PERMISSIONS.AUDIT_VIEW,
    ],
    [types_1.UserRole.OBSERVER]: [exports.PERMISSIONS.DASHBOARD_VIEW, exports.PERMISSIONS.ANALYTICS_VIEW],
};
exports.HTTP_STATUS = {
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
};
exports.ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    SLUG_ALREADY_EXISTS: 'SLUG_ALREADY_EXISTS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};
exports.DEFAULTS = {
    PAGINATION_PAGE: 1,
    PAGINATION_PER_PAGE: 20,
    PAGINATION_MAX_PER_PAGE: 100,
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 100,
    SESSION_MAX_AGE_MS: 30 * 24 * 60 * 60 * 1000,
    INVITATION_EXPIRY_MS: 7 * 24 * 60 * 60 * 1000,
    VERIFICATION_TOKEN_EXPIRY_MS: 24 * 60 * 60 * 1000,
    MAX_FILE_SIZE_BYTES: 100 * 1024 * 1024,
    RATE_LIMIT_WINDOW_MS: 60 * 1000,
    RATE_LIMIT_MAX_REQUESTS: 100,
};
